# Hadolint configuration file


# Ignored rules
#
# See https://github.com/hadolint/hadolint#rules for a list of available rules.
ignored:
  - DL3008      # warning: Pin versions in apt-get install (i.e. apt-get insall <package>=<version>)
  - DL4001      # warning: Either use Wget or Curl but not both
  - DL4006      # warning: Set the SHELL option -o pipefail before RUN with a pipe in it