
FROM ubuntu:18.04

# Docker image metadata
LABEL org.opencontainers.image.title="Rust"
LABEL org.opencontainers.image.description="Rust compiler and tools"
LABEL org.opencontainers.image.source="https://github.com/AutonomyOrg/docker-images/rust"
LABEL org.opencontainers.image.license=Apache-2.0
