
FROM rust:1.62-slim-buster

# Docker image metadata
LABEL org.opencontainers.image.title="Rust"
LABEL org.opencontainers.image.description="Rust compiler tools"
LABEL org.opencontainers.image.source="https://github.com/AutonomyOrg/docker-images/rust"
LABEL org.opencontainers.image.license=Apache-2.0
