# Autonomy
# Next-generation redistributive finance
#
# Handcrafted since 2022 by Autonomy Organisation <info@autonomy.org>
#
# This workflow aims at ensuring best coding practices, especially for
# Dockerfiles.

name: Check coding standards

on:
  # Execute this script on any pull request
  pull_request: 
  
  # Or execute this workflow on push to main branch
  push:
    branches:
      - 'main'

jobs:

  # Lint Dockerfiles
  lint-dockerfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          set-safe-directory: true

      - name: Run Hadolint 
        uses: hadolint/hadolint-action@v2.0.0
        with:
          config: ./.hadolint.yaml
          recursive: true
          dockerfile: Dockerfile