# This Github Actions script is triggered when new modifications are pushed to
# main branch. It aims at checking Dockerfile, so that to be sure best practices
# for Docker image engineering are applied.
#
# See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

name: Integrate new modifications

on:
  # Triggered on pull requests
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

  # Triggered on pushes to main or a featuer branch
  push:
    branches:
      - 'main'
      - 'feature**'

jobs:
  # Job used to check coding's best practices
  coding-standards:
    name: Check coding standards
    runs-on: ubuntu-latest

    steps:
      # Checkout repository with full history (not only the latest commit)
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          set-safe-directory: true

      # Install Hadolint package
      - name: Install Hadolint executable
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
          sudo chmod 755 /bin/hadolint

      # Execute Hadolint on modified Dockerfiles
      - name: Lint modified Dockerfile(s)
        run: |
          for dockerfilePath in $(find . -name Dockerfile); do
            echo "Linting $dockerfilePath"
            hadolint $dockerfilePath
          done;

    - name: Lint Dockerfiles recursively
      uses: hadolint/hadolint-action@v2.0.0
      with:
        recursive: true
        dockerfile: Dockerfile
